couchbase1:
  image: couchbase
  volumes:
    - ~/cbDay/node1:/opt/couchbase/var
couchbase2:
  image: couchbase
  volumes:
    - ~/cbDay/node2:/opt/couchbase/var
  ports:
    - 8091:8091
    - 8092:8092 
    - 8093:8093 
    - 11210:11210

