FROM    centos:centos6

# Enable Extra Packages for Enterprise Linux (EPEL) for CentOS
RUN     yum install -y epel-release

# Install Node.js and npm
RUN     yum install -y nodejs npm
RUN 	yum -y install git
# Install golang
RUN	yum install -y golang

# Application: travel-sample
RUN	mkdir ~/try-cb
RUN	git clone https://github.com/ToddGreenstein/try-cb-nodejs.git ~/try-cb
RUN	npm install node-gyp -g
RUN	npm install ~/try-cb
EXPOSE 3000 

# Application: go-beersample
RUN     mkdir ~/try-go
RUN     git clone git://github.com/couchbaselabs/beersample-go.git ~/try-go
EXPOSE 9980

# JAVA Environment
RUN	yum install -y wget
RUN	yum install -y java-1.8.0-openjdk
RUN	wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
RUN	sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
RUN	yum install -y apache-maven
RUN	mvn --version

